In [46]:
import numpy as np
import pandas as pd

In [47]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [48]:
import warnings
import pickle
warnings.filterwarnings("ignore")

In [49]:
data = pd.read_csv("fire-dataset_T.csv")
df = pd.DataFrame(data)

In [50]:
df

Unnamed: 0  FFMC    DMC     DC   ISI  temp    RH  wind  rain  class
0             0  90.1   51.2  424.1   6.2  24.6  43.0   1.8   0.0    1.0
1             1  79.7    4.3   15.2   1.7  24.0  54.0  18.0   0.1    0.0
2             2  84.9   18.2   55.0   3.0   5.3  70.0   4.5   0.0    1.0
3             3  79.9   13.8   36.1   2.4  28.0  70.0  15.0   0.0    0.0
4             4  89.4   23.2  120.9   9.7  35.0  62.0  19.0   0.0    1.0
..          ...   ...    ...    ...   ...   ...   ...   ...   ...    ...
618         618  93.5  149.3  728.6   8.1  28.3  26.0   3.1   0.0    1.0
619         619  28.6    1.3    6.9   0.0  25.0  89.0  13.0   2.5    0.0
620         620  94.5  139.4  689.1  20.0  28.9  29.0   4.9   0.0    1.0
621         621  93.8   23.0   42.7  15.7  38.0  35.0  15.0   0.0    1.0
622         622  90.6   18.2   30.5  13.4  31.0  42.0  21.0   0.0    1.0

[623 rows x 10 columns]

In [51]:
#df.drop(['X', 'Y','month','day'], axis=1, inplace=True)

In [52]:
df

Unnamed: 0  FFMC    DMC     DC   ISI  temp    RH  wind  rain  class
0             0  90.1   51.2  424.1   6.2  24.6  43.0   1.8   0.0    1.0
1             1  79.7    4.3   15.2   1.7  24.0  54.0  18.0   0.1    0.0
2             2  84.9   18.2   55.0   3.0   5.3  70.0   4.5   0.0    1.0
3             3  79.9   13.8   36.1   2.4  28.0  70.0  15.0   0.0    0.0
4             4  89.4   23.2  120.9   9.7  35.0  62.0  19.0   0.0    1.0
..          ...   ...    ...    ...   ...   ...   ...   ...   ...    ...
618         618  93.5  149.3  728.6   8.1  28.3  26.0   3.1   0.0    1.0
619         619  28.6    1.3    6.9   0.0  25.0  89.0  13.0   2.5    0.0
620         620  94.5  139.4  689.1  20.0  28.9  29.0   4.9   0.0    1.0
621         621  93.8   23.0   42.7  15.7  38.0  35.0  15.0   0.0    1.0
622         622  90.6   18.2   30.5  13.4  31.0  42.0  21.0   0.0    1.0

[623 rows x 10 columns]

In [53]:
df.isnull().values.any().sum()

0

In [54]:
nan_cols = [i for i in df.columns if df[i].isnull().any()]
nan_cols

[]

In [55]:
#df.fillna(df[nan_cols[0]].mean(),inplace=True)
df.isnull().values.any().sum()

0

In [56]:
df['DC'] = df['DC'].astype(float)
df

Unnamed: 0  FFMC    DMC     DC   ISI  temp    RH  wind  rain  class
0             0  90.1   51.2  424.1   6.2  24.6  43.0   1.8   0.0    1.0
1             1  79.7    4.3   15.2   1.7  24.0  54.0  18.0   0.1    0.0
2             2  84.9   18.2   55.0   3.0   5.3  70.0   4.5   0.0    1.0
3             3  79.9   13.8   36.1   2.4  28.0  70.0  15.0   0.0    0.0
4             4  89.4   23.2  120.9   9.7  35.0  62.0  19.0   0.0    1.0
..          ...   ...    ...    ...   ...   ...   ...   ...   ...    ...
618         618  93.5  149.3  728.6   8.1  28.3  26.0   3.1   0.0    1.0
619         619  28.6    1.3    6.9   0.0  25.0  89.0  13.0   2.5    0.0
620         620  94.5  139.4  689.1  20.0  28.9  29.0   4.9   0.0    1.0
621         621  93.8   23.0   42.7  15.7  38.0  35.0  15.0   0.0    1.0
622         622  90.6   18.2   30.5  13.4  31.0  42.0  21.0   0.0    1.0

[623 rows x 10 columns]

In [57]:
df = df.sample(frac = 1).reset_index(drop=True)
df.shape

(623, 10)

In [58]:
df.loc[df['class'] > 0, 'class'] = 1

In [59]:
x = df.iloc[:, 0:8].values
x

array([[274. ,  80.8,   3.4, ...,  29. ,  75. ,  16. ],
       [ 70. ,  92.5, 121.1, ...,  18.2,  46. ,   1.8],
       [598. ,  91.2,  48.3, ...,  11.7,  33. ,   4. ],
       ...,
       [312. ,  85.4,  25.4, ...,   4.6,  21. ,   8.5],
       [102. ,  91.8, 170.9, ...,  20.6,  59. ,   0.9],
       [407. ,  93.1, 157.3, ...,  24. ,  36. ,   3.1]])

In [60]:
y = df.iloc[:,-1].values.astype(int)
y

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,

In [61]:
df.to_csv('fire-dataset.csv')

In [62]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=40)
print('Train Data')
print(x_train.shape)
print('Test Data')
print(x_test.shape)

Train Data
(436, 8)
Test Data
(187, 8)


In [63]:
lr = LogisticRegression(max_iter=600, class_weight={0:9.0, 1:17})

In [64]:
lr.fit(x_train, y_train)

LogisticRegression(class_weight={0: 9.0, 1: 17}, max_iter=600)

In [65]:
pred = lr.predict(x_test)
pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1])

In [66]:
from sklearn import metrics
print("Acuraccy: ",metrics.accuracy_score(pred,y_test)*100)

Acuraccy:  77.54010695187165


In [67]:
pickle.dump(lr, open('Firemodel_T.sav','wb'))
pickle.dump(lr, open('Firemodel_T.pkl','wb'))